title: Cemu Graphic Packs
description: Official website of the Community Graphic Packs for Cemu, used to upscale and/or change your favorite Wii U games.
url: https://cemu-project.github.io/cemu_graphic_packs/
repository: cemu-project/cemu_graphic_packs

author:
  name: "Cemu Team and community contributors"

collections:
  - FAQ

Include:
  - /assets/images

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - watch_local.bat
